### PR TITLE
Ridvan fix null open test

### PR DESCRIPTION
**Pull request by rozaydin**
This PR reverts changes done within the context of null opens thus reduces the number of tests failing

### CODE REVIEW

**Comment by pinheadmz** [comment]
Hi guys. Lots of commits in this one! Anything you'd like to contribute back to hsd?

**Comment by rozaydin** [comment]
I have created PR to the wrong branch, my bad @pinheadmz sorry for the unnecessary noise

**Comment by pinheadmz** [comment]
Sure no prob.

**Comment by pinheadmz** [comment]
I'd like to finish up null opens pretty soon as well, would love to know if you guys have made progress on it or have some good tests?

**Comment by pinheadmz** [comment]
They should be mineable, this was my first test: https://hnsnetwork.com/txs/12f0b0cd96c1ffbcdda145fb3a3f8580b756805ba9c47836e5b018f857096dd7

The nulldata standardness bug was [fixed](https://github.com/handshake-org/hsd/pull/498) and released since version 2.2.0 which is a majority of the network as far as I can tell:

```
  '/hnsd:1.0.0/' => 19,
  '/hsd:2.0.2/' => 9,
  '/hsd:2.0.3/' => 1,
  '/hsd:2.1.1/' => 1,
  '/hsd:2.1.2/' => 2,
  '/hsd:2.1.3/' => 5,
  '/hsd:2.1.5/' => 31,
  '/hsd:2.2.0/' => 48,
  '/hsd:2.3.0/' => 36,
  '/hsd:2.4.0/' => 156,
  '/hsd:2.4.0/hmail.app/' => 1,
  '/hsd:2.4.0/sinpapeles/' => 3
```

... especially since the inflation bug was resolved, I am confident that all miners are running v.2.4.0 so maybe that was the thing we needed to ensure the miners upgraded ;-) Hopefully nulldata's will be confirmed like normal now.

**Comment by rozaydin** [comment]
@pinheadmz Let me collect some traces, on mainnet to better explain what we faced, I see your point but it's been sometime since we tested this, i can't remember exactly what went wrong and why we decided to rollback. will get back to you with data :)

**Pull request closed without merging**
