### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by hectorm**
Docker image based on node:10-alpine, ~110MB (~40MB gzipped)

### CODE REVIEW

**Comment by Thann** [comment]
leveldown has had issues in the past running on alpine because of libmusl, I'll try and see if I can repro those.

**Comment by bmillemathias** [comment]
Thanks for the work. That would be great to have regular update of the docker image also.

**Comment by Thann** [comment]
Hey! we just merged in my Dockerfile PR, but I want to discuss the additions you have, so we can add them if appropriate.

The only substantive difference I see is that you use the `hsd` user. I don't think this is necessary, because there shouldn't be anything secret inside the container that you would want to insulate from the main process by changing the user. (and that process has access to nothing outside the container)

If I'm missing something , please ping me and we can discuss it further =]

**Comment by tynes** [comment]
@hectorm Thank you for your contribution, but I am going to close this now that there is already a `Dockerfile` in the repo

**Pull request closed without merging**
