### PR TITLE
Update coveralls action

### PR DESCRIPTION
**Pull request by Falci**
I'm trying to fix the [Source not available](https://coveralls.io/builds/45317392/source?filename=lib%2Fprotocol%2Fconsensus.js#L4720) from Coveralls.

### CODE REVIEW

**Comment by pinheadmz** [comment]
I think you just have to be logged in to GitHub ? And/or logged in to coveralls. It's possible you might also need to be a repo owner ?

**Comment by pinheadmz** [comment]
0AAB1586-C3A7-4B87-9458-E9DD8B67B45A

this is what I see when I click that link

**Comment by Falci** [comment]
Hmm.. weird.. 

image

**Comment by Falci** [comment]
Yep, just need to login there as well 🤦‍♂️

**Comment by pinheadmz** [comment]
OK I think this is fine for now but I have issues with coveralls anyway, for example this pull request coveralls reports

'Overall coverage decreased (-4.1%) to 62.689%'

We may have some non-deterministic tests, but this kind of result is what makes coveralls useless ;-/

**Pull request merged**
