### PR TITLE
Docker Compose

### PR DESCRIPTION
**Pull request by Thann**
I setup automated builds on docker-hub, so this compose file will make setting up hsd & mining super simple =]

https://hub.docker.com/u/handshakeorg/

( Relies on #26 )

Getting started: 
1. Install https://github.com/NVIDIA/nvidia-docker
2. Run `docker-compose up -d`
3. Run `docker exec hsd_hsd_1 hsw-cli address default`
4. Edit `docker-compose.ym`l: Uncomment "miner" section and set COINBASE_ADDRESS to address from step 3
5. Run `docker-compose up -d` again
6. ???
7. Run `docker exec hsd_hsd_1 hsw-cli get --api-key=PASSWORD` too see your profit

### CODE REVIEW

**Comment by tynes** [comment]
Maybe move the files to a `docker` directory and then add a `README` with those instructions so that everybody will be able to see them in the future? Also profit for the win

**Comment by Thann** [comment]
I created the automated-builds on docker-hub, then manually built and pushed the images for testing =]

https://hub.docker.com/u/handshakeorg/

**Comment by Thann** [comment]
I'd be super down to move the files to another folder, but I don't think they clutter it up to bad, and I can add the info to the regular readme =]

**Comment by tynes** [comment]
I'm fine with whatever gets the info in a place where people can see

**Comment by tynes** [comment]
Hey @Thann, bumping this PR to see if you had any thoughts on its future, I'm feeling like `docker-compose` isn't the most useful thing for `hsd` right now because the other services in the `docker-compose.yml` are not being maintained

**Comment by tynes** [comment]
Closing due to no response. Can reopen if there is interest

**Pull request closed without merging**
