### PR TITLE
ci(tests): Update nodejs versions

### PR DESCRIPTION
**Pull request by Falci**
[Node v18.0.0 (Current)](https://nodejs.org/en/blog/release/v18.0.0/)

Update LTS versions: https://nodejs.org/en/about/releases/

### CODE REVIEW

**Comment by handshake-enthusiast** [comment]
In the meantime https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/docs/install.md:
>`hsd` requires Node.js v12 or higher.

1. Should we update it as well then?  
2. I'm not from the Node world. Does EOL mean that there is a strong reason to stop testing against it?  
3. Should https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/.github/workflows/docs.yml#L14 be updated as well?

**Comment by handshake-enthusiast** [comment]
I see that it's `ci(tests)`, but still:  

4. Should [package.json](https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/package.json#L20) and [package-lock.json](https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/package-lock.json) be updated as well?
```json
  "engines": {
    "node": ">=8.0.0"
  },
```

For me it's quite confusing that something is being tested against newest versions while still allowing old versions where the installation likely fails.

**Comment by handshake-enthusiast** [comment]
A recent issue https://github.com/handshake-org/hsd/issues/714#issuecomment-1099156888 which is related to my comment above.

**Comment by handshake-enthusiast** [comment]
https://handshake.org/download/ says:
>Node.js version 10+ is required to run: Execute `hsd-3.0.1/hsd/bin/hsd`  

([source code](https://github.com/handshake-org/handshake-web/blob/5e84d2ba67f2a4f02bdc22a9e8778b2a08fae260/download/index.html#L101))

**Comment by pinheadmz** [comment]
All good points @handshake-enthusiast I see from nodejs website that v12 is EOL in just a few days! (April 30)

So it does seem prudent to update all the places you found, 14 is the new minimum and that should be reflected in package.json, the docs, and all the CI scripts.

**Comment by nodech** [comment]
You could just add new version on the matrix:
```
        node-version: [12.x, 14.x, 16.x, 18.x]
```

> In the meantime https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/docs/install.md:
> 
> > `hsd` requires Node.js v12 or higher.
> 
>   1. Should we update it as well then?
> 
>   2. I'm not from the Node world. Does EOL mean that there is a strong reason to stop testing against it?
> 
>   3. Should https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/.github/workflows/docs.yml#L14 be updated as well?
>  4. Should [package.json](https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/package.json#L20) and [package-lock.json](https://github.com/Falci/hsd/blob/1fc2bc1f3ba3fab4dc81e8b93a7a049d0d409b40/package-lock.json) be updated as well?

1. I believe we don't. It just needs to state what's the minimum version supported. (If someone wants to use older machine/node after EOL it's their choice)
2. I believe we should test it against minim required version as well, because if it ever breaks we will see it in the tests and maybe fix it or maybe drop the support altogether.
3. That is only generating documentation, so it does not matter.
4. Yes, we need to update package.json to show that hsd needs at least nodejs v12.

**Comment by Falci** [comment]
Ok, here's the recent changes:

* added 12x back to test table;
* updated engine to >= 12.x
* build docs using 16.x

**Pull request merged**
