### PR TITLE
refactor: Use namestate methods for state comparison

### PR DESCRIPTION
**Pull request by Falci**
No extra features, just refactoring.

Inspired on [a comment](https://github.com/handshake-org/hsd/pull/679#issuecomment-1003605385) from a previous PR.

### CODE REVIEW

**Comment by pinheadmz** [comment]
Pretty nice clean up... looking for more:



https://github.com/handshake-org/hsd/blob/64e39a5c69d823b050bc5624ce0ab3163a220703/lib/wallet/wallet.js#L2020-L2026

https://github.com/handshake-org/hsd/blob/64e39a5c69d823b050bc5624ce0ab3163a220703/lib/wallet/wallet.js#L2281-L2284

https://github.com/handshake-org/hsd/blob/64e39a5c69d823b050bc5624ce0ab3163a220703/test/util/memwallet.js#L1186-L1189

**Comment by Falci** [comment]
> looking for more

What do you suggest here?

**Comment by pinheadmz** [comment]
I think the first can be `isReveal()` and the last two can be `isClosed()` ?

**Comment by Falci** [comment]
It's ok for [the first one](https://github.com/handshake-org/hsd/pull/683/files#diff-477870ca605732fc3986e0c6f460e400e31277ef813ad9cb5dbb784d4356af98R2018-R2019), but I think we should not change the others.

They are numeric comparison and could have some unexpected behaviour.

**Comment by pinheadmz** [comment]
suggestion: 

```diff
diff --git a/lib/covenants/namestate.js b/lib/covenants/namestate.js
index a4318132a..a79996265 100644
--- a/lib/covenants/namestate.js
+++ b/lib/covenants/namestate.js
@@ -182,6 +182,10 @@ class NameState extends bio.Struct {
     return this.state(height, network) === states.REVOKED;
   }
 
+  isRedeemable(height, network) {
+    return this.state(height, network) >= states.CLOSED;
+  }
+
   isClaimable(height, network) {
     assert((height >>> 0) === height);
     assert(network && network.names);
diff --git a/lib/wallet/wallet.js b/lib/wallet/wallet.js
index ab3d1326b..2e0c15ca7 100644
--- a/lib/wallet/wallet.js
+++ b/lib/wallet/wallet.js
@@ -2138,9 +2138,7 @@ class Wallet extends EventEmitter {
     if (ns.isExpired(height, network))
       throw new Error('Name has expired!');
 
-    const state = ns.state(height, network);
-
-    if (state < states.CLOSED)
+    if (!ns.isRedeemable(height, network))
       throw new Error('Auction is not yet closed.');
 
     const reveals = await this.txdb.getReveals(nameHash);
@@ -2271,9 +2269,7 @@ class Wallet extends EventEmitter {
       if (ns.isExpired(height, network))
         continue;
 
-      const state = ns.state(height, network);
-
-      if (state < states.CLOSED)
+      if (!ns.isRedeemable(height, network))
         continue;
 
       if (!own)
diff --git a/test/util/memwallet.js b/test/util/memwallet.js
index 1c614b84e..258ee24b2 100644
--- a/test/util/memwallet.js
+++ b/test/util/memwallet.js
@@ -1181,9 +1181,7 @@ class MemWallet {
     if (ns.isExpired(height, network))
       throw new Error('Name has expired!');
 
-    const state = ns.state(height, network);
-
-    if (state < states.CLOSED)
+    if (!ns.isRedeemable(height, network))
       throw new Error('Auction is not yet closed.');
 
     const reveals = this.getReveals(nameHash);

```

**Review by pinheadmz — APPROVED** [review]
ACK 849113ce9ec8df8764006d41c263e4598fbdcd48
<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 849113ce9ec8df8764006d41c263e4598fbdcd48
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmHcggUACgkQ5+KYS2KJ
yToXAg/+MiZGyAO1oUIIMGKow7wA4wcjwS75ptdH+WmcXs4ksevIQU72EB7Pnjcn
Pu55DTXhbG5UT/T8LeUWLSR0nJD/YS+/72pSvMMpYoxGgUZbIe+xq3vK4Ijtjjgq
gHsISd94/i8ntdMNM9mGufFtPmx4OpVnvxjJFxma1cPM5RMniuqPCFtl5/sEW2Zz
DQqvGIHewB5MyPA51Kl/+k2vCujfecCE5UXp/uUEtzc+qPFjv9g1y+NJwEONV4/e
7GBJ85nT3h+PqjfcD5xaphrLHI+3nVIZM+ubDOeKrg8nHENY0CRXSvyerRMT6Aza
kFTuGo2ndrkKzpbEp92pSAjKByXaLL3LVg5P5nmln5heN78offjdTGPWHXk6FVrQ
7vRX2mCEt3yOdTYUbofSLROqYDQ0Pe/L+t6fQTLXEzuN1GSNPLEZUaAzRmghkKQC
x/5DqOqUhFzT0xdZ2BFbVqL0JDJAWEy+K+w5LHxLw7PmM2WfBKX4Yyadq8A4s8EH
i4ZPk81axQdLt6yhIC38R5ZLir5MHKmCkBnLl9rPt7nvR3+CpzQYUhicLmooKdAn
/wrtyjAwdmj7Wv9QxnJht4t1Tt2bLWP/K4DK3wpwecqhwQ1Vmp9aFeIRSf3iULIT
4MSHvFA9UvD+IwswUXw2JtPZc1zomvP5g8ya175DiwX+U9jbgdY=
=rfgH
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Comment by pinheadmz** [comment]
I noticed in the coverage report that a lot of the wallet `make___()` errors are not covered (eg "Auction is not yet open" and "Name has not reached bidding phase", etc). This could be another "good first issue" that would be easy to do and get a few more lines covered.

**Pull request merged**
