### PR TITLE
Update README.md For Fixing npm python2 issue

### PR DESCRIPTION
**Pull request by hannibalhuang**
Add error fix for npm python2 dependency if you ran into problem like I did:

> bdb@1.1.7 install /Users/zhipeng/Workspace/hsd/node_modules/bdb
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1001:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:405:11)
gyp ERR! stack     at Socket.emit (events.js:193:13)
gyp ERR! stack     at Pipe._handle.close (net.js:614:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/11.13.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhipeng/Workspace/hsd/node_modules/bdb
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.3.4 (node_modules/unbound):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.3.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bdb@1.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bdb@1.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhipeng/.npm/_logs/2019-04-07T00_18_34_789Z-debug.log

### CODE REVIEW

**Comment by tynes** [comment]
Hey @hannibalhuang thanks for the PR. Do you have a more simple way to achieve the same result? While that bash command may work, it would be more ideal if there was a more simple way to do it

**Comment by hannibalhuang** [comment]
> Hey @hannibalhuang thanks for the PR. Do you have a more simple way to achieve the same result? While that bash command may work, it would be more ideal if there was a more simple way to do it

Well this is what I googled and used :P

**Comment by tynes** [comment]
Maybe something more like this:

---

`node-gyp` is used to compile native code and requires Python 2.7. If your machine natively supports Python 3, configure `npm` using the command:

```
$ npm config set python /path/to/executable/python2.7
```

You can determine the native version of Python using:

```
$ python --version
```

See [node-gyp](https://github.com/nodejs/node-gyp) documentation for more information.

---

Thoughts @boymanjor?

**Comment by hannibalhuang** [comment]
> Maybe something more like this:
> 
> `node-gyp` is used to compile native code and requires Python 2.7. If your machine natively supports Python 3, configure `npm` using the command:
> 
> ```
> $ npm config set python /path/to/executable/python2.7
> ```
> You can determine the native version of Python using:
> 
> ```
> $ python --version
> ```
> See the [node-gyp](https://github.com/nodejs/node-gyp) documentation for more information.
> 
> Thoughts @boymanjor?

well seems neat to me :)

**Comment by boymanjor** [comment]
Closing in favor of #183

**Pull request closed without merging**
